import fs from "node:fs";
import path from "node:path";
import { type FailureSignal } from "./classifier.ts";
import { type ThreadInfo } from "./codexState.ts";
import { commandExists, runCommand } from "./exec.ts";
import { bundlesDir } from "./paths.ts";
import { latestSnapshotPath } from "./prompt.ts";
import { readRecentThreadContext, renderRecentThreadContext, type RecentThreadContext } from "./threadContext.ts";

export type RecoveryBundleInput = {
  home?: string;
  thread: ThreadInfo | null;
  signal: FailureSignal;
  prompt: string;
  bundleDir?: string;
  projectRoot?: string;
};

const EXCLUDED_DIRS = new Set([
  ".git",
  "node_modules",
  "dist",
  "coverage",
  ".next",
  "target",
  ".cache",
  "site-dist"
]);

const IMPORTANT_FILE_RE = /(^|\/)(README|AGENTS|GEMINI|CLAUDE|package|tsconfig|Cargo|pyproject|requirements|Makefile|Dockerfile|compose|\.env\.example)|(^|\/)(src|bin|docs|test|tests)\//i;
const TEXT_FILE_RE = /\.(md|txt|js|mjs|cjs|ts|tsx|json|toml|yaml|yml|rs|py|sh|sql|html|css)$/i;

export function plannedBundleDir(home: string | undefined, threadId: string): string {
  const safeId = threadId.replace(/[^a-z0-9-]/gi, "_");
  return path.join(bundlesDir(home), `${safeId}-${Date.now()}`);
}

export function writeRecoveryBundle(input: RecoveryBundleInput): string {
  const threadId = input.thread?.id || input.signal.threadId || "unknown";
  const dir = input.bundleDir || plannedBundleDir(input.home, threadId);
  const root = input.projectRoot || input.thread?.cwd || process.cwd();
  fs.mkdirSync(dir, { recursive: true });

  const files = listProjectFiles(root);
  const selected = selectImportantFiles(files);
  const gitStatus = readGit(root, ["status", "--short"]);
  const gitDiffStat = readGit(root, ["diff", "--stat"]);
  const gitDiff = limitText(readGit(root, ["diff", "--no-ext-diff"]), 200_000);
  const latestSnapshot = input.thread ? latestSnapshotPath(input.thread.id, input.home) : null;
  const recentThreadContext = readRecentThreadContext(input.thread, { home: input.home });

  fs.writeFileSync(path.join(dir, "project-files.txt"), `${files.join("\n")}\n`);
  fs.writeFileSync(path.join(dir, "git-status.txt"), gitStatus || "not a git repository or no changes\n");
  fs.writeFileSync(path.join(dir, "git-diff-stat.txt"), gitDiffStat || "no diff stat\n");
  fs.writeFileSync(path.join(dir, "git-diff.patch"), gitDiff || "no diff\n");
  fs.writeFileSync(path.join(dir, "selected-files.md"), renderSelectedFiles(root, selected));
  fs.writeFileSync(path.join(dir, "RECENT_THREAD_CONTEXT.md"), renderRecentThreadContext(recentThreadContext));
  fs.writeFileSync(path.join(dir, "RECOVERY.md"), renderRecoveryReadme({
    thread: input.thread,
    signal: input.signal,
    root,
    prompt: input.prompt,
    latestSnapshot,
    recentThreadContext,
    selectedCount: selected.length,
    fileCount: files.length
  }));

  return dir;
}

function listProjectFiles(root: string): string[] {
  const result = commandExists("rg")
    ? runCommand("rg", ["--files", "-g", "!node_modules", "-g", "!.git", "-g", "!dist", "-g", "!coverage"], { cwd: root, timeoutMs: 5000 })
    : runCommand("find", [".", "-type", "f"], { cwd: root, timeoutMs: 5000 });
  if (result.status !== 0) return [];
  return result.stdout
    .split("\n")
    .map((line) => line.trim().replace(/^\.\//, ""))
    .filter(Boolean)
    .filter((file) => !file.split(/[\\/]/).some((part) => EXCLUDED_DIRS.has(part)))
    .sort()
    .slice(0, 1000);
}

function selectImportantFiles(files: string[]): string[] {
  return files
    .filter((file) => IMPORTANT_FILE_RE.test(file) && TEXT_FILE_RE.test(file))
    .slice(0, 80);
}

function renderSelectedFiles(root: string, files: string[]): string {
  let budget = 300_000;
  const parts = ["# Selected Project Files\n"];
  for (const file of files) {
    if (budget <= 0) break;
    const absolute = path.join(root, file);
    let text = "";
    try {
      const stat = fs.statSync(absolute);
      if (!stat.isFile() || stat.size > 100_000) continue;
      text = fs.readFileSync(absolute, "utf8");
    } catch {
      continue;
    }
    const clipped = limitText(text, Math.min(30_000, budget));
    budget -= clipped.length;
    parts.push(`\n## ${file}\n\n\`\`\`\n${clipped}\n\`\`\`\n`);
  }
  return parts.join("");
}

function renderRecoveryReadme(input: {
  thread: ThreadInfo | null;
  signal: FailureSignal;
  root: string;
  prompt: string;
  latestSnapshot: string | null;
  recentThreadContext: RecentThreadContext;
  selectedCount: number;
  fileCount: number;
}): string {
  return `# Codex Recovery Bundle

Generated by Codex Context Guardian.

## Thread

- id: ${input.thread?.id || input.signal.threadId || "unknown"}
- title: ${input.thread?.title || "unknown"}
- cwd: ${input.root}
- model: ${input.thread?.model || "unknown"}
- tokensUsed: ${input.thread?.tokensUsed ?? "unknown"}

## Failure Signal

- kind: ${input.signal.kind}
- confidence: ${input.signal.confidence}
- reason: ${input.signal.reason}
- sourceLogId: ${input.signal.sourceLogId || "unknown"}

## Bundle Contents

- project-files.txt: ${input.fileCount} project files, capped for recovery.
- RECENT_THREAD_CONTEXT.md: latest active goal and recent user/assistant messages from the source rollout. Read this first.
- selected-files.md: ${input.selectedCount} important text files.
- git-status.txt: current git status.
- git-diff-stat.txt: diff summary.
- git-diff.patch: capped working tree diff.
- latest snapshot: ${input.latestSnapshot || "unavailable"}
- source rollout: ${input.recentThreadContext.rolloutPath || "unavailable"}

## Priority Recovery Evidence

- First read RECENT_THREAD_CONTEXT.md.
- Treat the latest active goal and latest user messages as higher priority than older project documents or early conversation directions.
- If RECENT_THREAD_CONTEXT.md says the user changed direction, continue the newer direction and do not revive abandoned earlier approaches.

## Recovery Prompt

\`\`\`
${input.prompt}
\`\`\`
`;
}

function readGit(root: string, args: string[]): string {
  const result = runCommand("git", args, { cwd: root, timeoutMs: 5000 });
  return result.status === 0 ? result.stdout : "";
}

function limitText(text: string, maxChars: number): string {
  if (text.length <= maxChars) return text;
  return `${text.slice(0, maxChars)}\n[truncated]`;
}
